# Generated by Django 6.0.1 on 2026-02-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='premium',
            field=models.IntegerField(default=0, verbose_name='Punkty Premium'),
        ),
    ]
