# Generated by Django 6.0.3 on 2026-03-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_logo',
            field=models.ImageField(blank=True, null=True, upload_to='user_logos/', verbose_name='Plik loga'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_custom_logo',
            field=models.BooleanField(default=False, verbose_name='Ma wykupione własne logo'),
        ),
    ]
