# Generated by Django 6.0.3 on 2026-03-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_custom_logo_customuser_has_custom_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='logo_position',
            field=models.CharField(choices=[('right', 'Po prawej stronie tytułu'), ('left', 'Po lewej stronie tytułu'), ('top_center', 'Wyśrodkowane na górze (nad tytułem)')], default='right', max_length=20, verbose_name='Pozycja loga'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='logo_width',
            field=models.IntegerField(default=45, verbose_name='Szerokość loga (mm)'),
        ),
    ]
