# Generated by Django 6.0.3 on 2026-03-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_logo_position_customuser_logo_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='logo_height',
            field=models.IntegerField(default=20, verbose_name='Wysokość loga (mm)'),
        ),
    ]
