# Generated by Django 6.0.3 on 2026-03-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_logo_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme_color',
            field=models.CharField(default='#1565C0', max_length=7, verbose_name='Kolor motywu (HEX)'),
        ),
    ]
