# Generated by Django 6.0.3 on 2026-03-14 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_theme_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_logos/', verbose_name='Plik loga')),
                ('width', models.IntegerField(default=45, verbose_name='Szerokość (mm)')),
                ('height', models.IntegerField(default=20, verbose_name='Wysokość (mm)')),
                ('position', models.CharField(choices=[('right', 'Po prawej stronie tytułu'), ('left', 'Po lewej stronie tytułu'), ('top_center', 'Wyśrodkowane na górze (nad tytułem)')], default='right', max_length=20, verbose_name='Pozycja')),
                ('theme_color', models.CharField(default='#1565C0', max_length=7, verbose_name='Kolor motywu (HEX)')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nazwa własna loga (np. marka)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Domyślne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Logo użytkownika',
                'verbose_name_plural': 'Logotypy użytkownika',
            },
        ),
    ]
