# Generated by Django 6.0.3 on 2026-03-14 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_migrate_existing_logos'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_signatures/', verbose_name='Plik podpisu')),
                ('width', models.IntegerField(default=60, verbose_name='Szerokość (mm)')),
                ('height', models.IntegerField(default=30, verbose_name='Wysokość (mm)')),
                ('position', models.CharField(choices=[('bottom_right', 'Po prawej na dole'), ('bottom_left', 'Po lewej na dole'), ('bottom_center', 'Wyśrodkowane na dole')], default='bottom_right', max_length=20, verbose_name='Pozycja')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nazwa podpisu (np. Jan Kowalski)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Domyślne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Podpis użytkownika',
                'verbose_name_plural': 'Podpisy użytkownika',
            },
        ),
    ]
