# Generated by Django 6.0.3 on 2026-03-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usersignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_logo_on_pdf',
            field=models.BooleanField(default=True, verbose_name='Pokazuj logo na PDF'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_signature_on_pdf',
            field=models.BooleanField(default=True, verbose_name='Pokazuj podpis na PDF'),
        ),
    ]
