# Generated by Django 6.0.3 on 2026-03-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_show_logo_on_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discount_percent',
            field=models.IntegerField(default=0, verbose_name='Zniżka procentowa (%)'),
        ),
    ]
