# Generated by Django 5.2.10 on 2026-02-22 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Numer faktury')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota netto')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota VAT')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota brutto')),
                ('points_added', models.IntegerField(default=0, verbose_name='Dodane punkty')),
                ('ksef_reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numer referencyjny KSeF')),
                ('ksef_status', models.CharField(choices=[('pending', 'Oczekująca'), ('sent', 'Wysłana do KSeF'), ('accepted', 'Zaakceptowana przez KSeF'), ('rejected', 'Odrzucona przez KSeF'), ('cancelled', 'Anulowana')], default='pending', max_length=20, verbose_name='Status KSeF')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Data wystawienia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_name', models.CharField(max_length=255, verbose_name='Nazwa nabywcy')),
                ('buyer_nip', models.CharField(max_length=20, verbose_name='NIP nabywcy')),
                ('buyer_address', models.TextField(verbose_name='Adres nabywcy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Faktura',
                'verbose_name_plural': 'Faktury',
                'ordering': ['-issue_date', '-id'],
            },
        ),
    ]
