# Generated by Django 6.0.3 on 2026-03-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_paypalorder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_proforma',
            field=models.BooleanField(default=False, verbose_name='Proforma'),
        ),
    ]
