# Generated by Django 6.0.3 on 2026-03-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_is_proforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='service_name',
            field=models.CharField(default='Wyznaczenie resursu UTB', max_length=255, verbose_name='Nazwa usługi'),
        ),
    ]
