# Generated by Django 6.0.3 on 2026-03-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='recipient_address',
            field=models.TextField(blank=True, verbose_name='Adres odbiorcy'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nazwa odbiorcy'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='service_name',
            field=models.CharField(default='Wyznaczenie resursu UTB GTU_12', max_length=255, verbose_name='Nazwa usługi'),
        ),
    ]
