# Generated by Django 6.0.3 on 2026-03-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_recipient_address_invoice_recipient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(choices=[('paid', 'Zapłacono przelewem'), ('7_days', 'Do zapłaty w ciągu 7 dni'), ('14_days', 'Do zapłaty w ciągu 14 dni')], default='paid', max_length=20, verbose_name='Warunki płatności'),
        ),
    ]
