# Generated by Django 6.0.3 on 2026-03-15 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoice_payment_terms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusPointsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod bonusowy')),
                ('points', models.IntegerField(verbose_name='Liczba punktów')),
                ('is_active', models.BooleanField(default=True, verbose_name='Czy aktywny?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Data użycia')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_codes', to=settings.AUTH_USER_MODEL, verbose_name='Użyty przez')),
            ],
            options={
                'verbose_name': 'Kod bonusowy',
                'verbose_name_plural': 'Kody bonusowe',
            },
        ),
    ]
