# Generated by Django 6.0.3 on 2026-03-16 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_bonuspointscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='corrected_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='invoices.invoice', verbose_name='Korygowana faktura'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='correction_reason',
            field=models.TextField(blank=True, verbose_name='Powód korekty'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_correction',
            field=models.BooleanField(default=False, verbose_name='Korekta'),
        ),
    ]
