# Generated by Django 6.0.3 on 2026-04-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_correction_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ksef_invoice_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hash faktury KSeF (Base64)'),
        ),
    ]
