# Generated by Django 6.0.3 on 2026-04-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_invoice_ksef_invoice_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('paid', 'Zapłacono przelewem'), ('7_days', 'Do zapłaty w ciągu 7 dni'), ('14_days', 'Do zapłaty w ciągu 14 dni'), ('30_days', 'Do zapłaty w ciągu 30 dni')], default='', max_length=20, verbose_name='Warunki płatności'),
        ),
    ]
