# Generated by Django 6.0.1 on 2026-02-16 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa kalkulatora')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('definition', models.JSONField(verbose_name='Definicja kalkulatora')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('premium_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Koszt premium (punktów)')),
            ],
            options={
                'verbose_name': 'Definicja kalkulatora',
                'verbose_name_plural': 'Definicje kalkulatorów',
            },
        ),
        migrations.CreateModel(
            name='CalculatorResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(verbose_name='Dane wejściowe')),
                ('output_data', models.JSONField(verbose_name='Dane wyjściowe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data ostatniej aktualizacji')),
                ('calculator_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='calculators.calculatordefinition', verbose_name='Definicja kalkulatora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_results', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Wynik kalkulatora',
                'verbose_name_plural': 'Wyniki kalkulatorów',
                'ordering': ['-created_at'],
            },
        ),
    ]
