# Generated by Django 6.0.1 on 2026-02-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa jednostki')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='Symbol jednostki')),
                ('unit_type', models.CharField(choices=[('length', 'Długość'), ('mass', 'Masa'), ('time', 'Czas'), ('area', 'Powierzchnia'), ('volume', 'Objętość'), ('force', 'Siła'), ('pressure', 'Ciśnienie'), ('energy', 'Energia'), ('power', 'Moc'), ('temperature', 'Temperatura'), ('currency', 'Waluta'), ('dimensionless', 'Bezjednostkowe')], max_length=50, verbose_name='Typ jednostki')),
                ('conversion_factor', models.DecimalField(decimal_places=10, help_text='Współczynnik konwersji do podstawowej jednostki typu (np. dla długości: metra).', max_digits=20)),
            ],
            options={
                'verbose_name': 'Jednostka',
                'verbose_name_plural': 'Jednostki',
                'unique_together': {('unit_type', 'name')},
            },
        ),
    ]
