# Generated by Django 6.0.1 on 2026-02-16 19:24

from django.db import migrations
from decimal import Decimal


def populate_initial_units(apps, schema_editor):
    Unit = apps.get_model('calculators', 'Unit')

    # Mass
    Unit.objects.get_or_create(name='Kilogram', symbol='kg', unit_type='mass', conversion_factor=Decimal(1)) # Base unit for mass
    Unit.objects.get_or_create(name='Gram', symbol='g', unit_type='mass', conversion_factor=Decimal('0.001'))
    Unit.objects.get_or_create(name='Tonne', symbol='ton', unit_type='mass', conversion_factor=Decimal('1000'))
    Unit.objects.get_or_create(name='Pound', symbol='lb', unit_type='mass', conversion_factor=Decimal('0.45359237')) # 1 lb = 0.45359237 kg

    # Time
    Unit.objects.get_or_create(name='Year', symbol='year', unit_type='time', conversion_factor=Decimal(1)) # Base unit for time
    Unit.objects.get_or_create(name='Day', symbol='day', unit_type='time', conversion_factor=Decimal('1') / Decimal(365)) # 1 day = 1/365 year
    Unit.objects.get_or_create(name='Hour', symbol='hour', unit_type='time', conversion_factor=Decimal('1') / Decimal(8760)) # 1 hour = 1/8760 year (365*24)
    Unit.objects.get_or_create(name='Minute', symbol='min', unit_type='time', conversion_factor=Decimal('1') / Decimal(525600)) # 1 min = 1/525600 year
    Unit.objects.get_or_create(name='Second', symbol='sec', unit_type='time', conversion_factor=Decimal('1') / Decimal(31536000)) # 1 sec = 1/31536000 year
    
    # Dimensionless/Counts
    Unit.objects.get_or_create(name='Cycle', symbol='cycle', unit_type='dimensionless', conversion_factor=Decimal(1)) # Base unit for cycles
    Unit.objects.get_or_create(name='Cycles per Shift', symbol='cycle_per_shift', unit_type='dimensionless', conversion_factor=Decimal(1)) # Base unit for cycle rate

    # Length
    Unit.objects.get_or_create(name='Meter', symbol='m', unit_type='length', conversion_factor=Decimal(1)) # Base unit for length
    Unit.objects.get_or_create(name='Centimeter', symbol='cm', unit_type='length', conversion_factor=Decimal('0.01'))
    Unit.objects.get_or_create(name='Millimeter', symbol='mm', unit_type='length', conversion_factor=Decimal('0.001'))
    Unit.objects.get_or_create(name='Kilometer', symbol='km', unit_type='length', conversion_factor=Decimal('1000'))
    Unit.objects.get_or_create(name='Foot', symbol='ft', unit_type='length', conversion_factor=Decimal('0.3048'))
    Unit.objects.get_or_create(name='Inch', symbol='inch', unit_type='length', conversion_factor=Decimal('0.0254'))

def reverse_initial_units(apps, schema_editor):
    Unit = apps.get_model('calculators', 'Unit')
    Unit.objects.filter(symbol__in=[
        'kg', 'g', 'ton', 'lb',
        'year', 'day', 'hour', 'min', 'sec',
        'cycle', 'cycle_per_shift',
        'm', 'cm', 'mm', 'km', 'ft', 'inch',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0002_unit'),
    ]

    operations = [
        migrations.RunPython(populate_initial_units, reverse_initial_units),
    ]
