# Generated by Django 6.0.1 on 2026-02-16 19:41
import json
from django.db import migrations

# ... (get_common_fields definition remains the same) ...
def get_common_fields():
    return {
        "wykonawca": {"type": "text", "label": "Wykonawca", "required": True},
        "uwagi": {"type": "text", "label": "Uwagi", "required": False},
        "spec": {"type": "radio", "label": "Czy chcesz wyznaczyć resurs po pierwszym przeglądzie specjalnym?", "options": [{"label": "Tak", "value": 1}, {"label": "Nie", "value": 0}], "default_value": 0},
        "ponowny_resurs": {"type": "radio", "label": "Czy chcesz wykonać ponowne wyznaczenie resursu?", "options": [{"label": "Tak", "value": 1}, {"label": "Nie", "value": 0}], "default_value": 0},
        "data_resurs": {"type": "date", "label": "Data wyznaczenia ostatniego resursu", "required": False},
        "ostatni_resurs": {"type": "number", "label": "Procent wykorzystania z ostatnich wykonanych obliczeń resursu [%]", "required": False},
        "nr_fabryczny": {"type": "text", "label": "Nr fabryczny", "required": True},
        "q_max": {"type": "number", "label": "Udźwig maksymalny [kg]", "required": True, "unit_type": "mass", "default_unit": "kg"},
        "lata_pracy": {"type": "number", "label": "Ilość przepracowanych lat", "required": True, "unit_type": "time", "default_unit": "year"},
        "ilosc_cykli": {"type": "number", "label": "Ilość odbytych cykli", "required": True, "unit_type": "dimensionless", "default_unit": "cycle"},
        "cykle_zmiana": {"type": "number", "label": "Ilość cykli na zmianę", "required": False, "unit_type": "dimensionless", "default_unit": "cycle_per_shift"},
        "dni_robocze": {"type": "number", "label": "Ilość dni roboczych w roku", "required": False, "unit_type": "time", "default_unit": "day"},
        "tryb_pracy": {"type": "select", "label": "Tryb pracy", "options": ["jednozmianowy", "dwuzmianowy", "trzyzmianowy"], "required": False},
        "sposob_rejestracji": {"type": "select", "label": "Sposób rejestracji", "options": ["Rejestrowanie przyrządami", "Rejestrowanie w dzienniku, łącznie ze stosowaniem licznika", "Rejestrowanie na podstawie procesu technologicznego", "Rejestrowanie na podstawie informacji o produkcji", "Informacja o warunkach eksploatacji jest niekompletna", "Brak informacji o historii urządzenia"], "required": True},
        "gnp": {"type": "select", "label": "Grupa natężenia pracy", "options": ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8"], "required": True},
        "stan_obciazenia": {"type": "select", "label": "Stan obciążenia", "options": ["Q1-lekki", "Q2-przeciętny", "Q3-ciężki", "Q4-bardzo ciężki"], "required": True},
        "q_1": {"type": "number", "label": "Ciężar dla cykli C(i=1) [kg]", "unit_type": "mass", "default_unit": "kg"}, "c_1": {"type": "number", "label": "% cykli C(i=1)"},
        "q_2": {"type": "number", "label": "Ciężar dla cykli C(i=2) [kg]", "unit_type": "mass", "default_unit": "kg"}, "c_2": {"type": "number", "label": "% cykli C(i=2)"},
        "q_3": {"type": "number", "label": "Ciężar dla cykli C(i=3) [kg]", "unit_type": "mass", "default_unit": "kg"}, "c_3": {"type": "number", "label": "% cykli C(i=3)"},
        "q_4": {"type": "number", "label": "Ciężar dla cykli C(i=4) [kg]", "unit_type": "mass", "default_unit": "kg"}, "c_4": {"type": "number", "label": "% cykli C(i=4)"},
        "q_5": {"type": "number", "label": "Ciężar dla cykli C(i=5) [kg]", "unit_type": "mass", "default_unit": "kg"}, "c_5": {"type": "number", "label": "% cykli C(i=5)"},
        "konstrukcja": {"type": "radio", "label": "Czy konstrukcja stalowa jest zdeformowana?", "options": [{"label": "Tak", "value": 1}, {"label": "Nie", "value": 0}], "required": True},
        "automatyka": {"type": "radio", "label": "Czy automatyka jest sprawna?", "options": [{"label": "Tak", "value": 1}, {"label": "Nie", "value": 0}, {"label": "N/D", "value": -1}], "required": True},
        "sworznie": {"type": "radio", "label": "Czy sworznie/połączenia są w dobrym stanie?", "options": [{"label": "Tak", "value": 1}, {"label": "Nie", "value": 0}], "required": True},
        "ciegna": {"type": "radio", "label": "Czy cięgna (liny/łańcuchy) są w dobrym stanie?", "options": [{"label": "Tak", "value": 1}, {"label": "Nie", "value": 0}, {"label": "N/D", "value": -1}], "required": True},
        "eksploatacja": {"type": "radio", "label": "Czy urządzenie jest eksploatowane zgodnie z przeznaczeniem?", "options": [{"label": "Tak", "value": 1}, {"label": "Nie", "value": 0}], "required": True},
    }

def get_calculator_definitions():
    # ... (definitions for suwnica, wciagarka, zuraw) ...
    suwnica_fields = get_common_fields()
    # ...
    wciagarka_fields = get_common_fields()
    # ...
    zuraw_fields = get_common_fields()
    # ...

    # Definition for Dzwig
    dzwig_fields = {
        "typ": {"type": "select", "label": "Typ dźwigu", "options": ["hydrauliczny", "elektryczny", "mechaniczny-zębatkowy", "mechaniczny-śrubowy"]},
        "przeznaczenie": {"type": "select", "label": "Przeznaczenie dźwigu", "options": ["dźwig osobowy", "dźwig towarowy", "dźwig osobowo-towarowy", "transport osób niepełnosprawnych"]},
        "operator": {"type": "select", "label": "Rodzaj obsługi", "options": ["jazda z operatorem", "jazda bez operatora", "bez prawa jazdy w kabinie"]},
        "budynek": {"type": "select", "label": "Miejsce zabudowy", "options": ["budynek mieszkalny", "budynek firmowy", "budynek administracji publicznej", "budynek użyteczności publicznej", "budowa", "magazyn", "pojazd"]},
        "rok_budowy": {"type": "number", "label": "Rok budowy"},
        "przystanki": {"type": "number", "label": "Ilość przystanków"},
        "liczba_dzwigow": {"type": "number", "label": "Liczba dźwigów"},
        "h_pod": {"type": "number", "label": "Wysokość podnoszenia [m]", "unit_type": "length", "default_unit": "m"},
        "v_jaz": {"type": "number", "label": "Prędkość jazdy [m/min]", "unit_type": "speed", "default_unit": "m/min"}, # Need to add speed units
        "pyt_motogodzin": {"type": "radio", "label": "Czy dźwig posiada licznik motogodzin?", "options": [{"label": "Tak", "value": 1}, {"label": "Nie", "value": 0}]},
        "licznik_pracy": {"type": "number", "label": "Łączna ilość motogodzin [h]", "unit_type": "time", "default_unit": "hour"},
        # ... other dzwig specific fields ...
    }
    dzwig_fields.update(get_common_fields()) # Add common fields

    # Definition for Dzwignik
    dzwignik_fields = {
        "typ": {"type": "select", "label": "Typ mechanizmu dźwignika", "options": ["zębatkowy", "śrubowy", "tłokowy-hydrauliczny", "dźwigniowy"]},
        "h_max": {"type": "number", "label": "Maksymalna wysokość podnoszenia [m]", "unit_type": "length", "default_unit": "m"},
        "v_pod": {"type": "number", "label": "Prędkość podnoszenia/opuszczania [m/min]", "unit_type": "speed", "default_unit": "m/min"},
        "max_cykle_prod": {"type": "number", "label": "Graniczna ilość cykli od producenta"},
        "szczelnosc": {"type": "radio", "label": "Czy układ hydrauliczny jest szczelny?", "options": [{"label": "Tak", "value": 1}, {"label": "Nie", "value": 0}, {"label": "N/D", "value": -1}]},
        "hamulce": {"type": "radio", "label": "Czy układ hamulcowy jest sprawny?", "options": [{"label": "Tak", "value": 1}, {"label": "Nie", "value": 0}, {"label": "N/D", "value": -1}]},
        # ... h_1-h_5, cc_1-cc_5 for Hd calculator ...
    }
    dzwignik_fields.update(get_common_fields())
    
    return [
        {"name": "Suwnica", "slug": "suwnica", "description": "Kalkulator resursu dla suwnic.", "premium_cost": 10.00, "definition": {"fields": suwnica_fields}},
        {"name": "Wciągarka", "slug": "wciagarka", "description": "Kalkulator resursu dla wciągarek.", "premium_cost": 10.00, "definition": {"fields": wciagarka_fields}},
        {"name": "Żuraw", "slug": "zuraw", "description": "Kalkulator resursu dla żurawi.", "premium_cost": 15.00, "definition": {"fields": zuraw_fields}},
        {"name": "Dźwig", "slug": "dzwig", "description": "Kalkulator resursu dla dźwigów.", "premium_cost": 20.00, "definition": {"fields": dzwig_fields}},
        {"name": "Dźwignik", "slug": "dzwignik", "description": "Kalkulator resursu dla dźwigników.", "premium_cost": 15.00, "definition": {"fields": dzwignik_fields}},
    ]

def populate_calculator_definitions(apps, schema_editor):
    CalculatorDefinition = apps.get_model('calculators', 'CalculatorDefinition')
    definitions = get_calculator_definitions()

    for calc_def in definitions:
        CalculatorDefinition.objects.get_or_create(
            slug=calc_def["slug"],
            defaults={
                "name": calc_def["name"],
                "description": calc_def["description"],
                "premium_cost": calc_def["premium_cost"],
                "definition": calc_def["definition"]
            }
        )

def reverse_calculator_definitions(apps, schema_editor):
    CalculatorDefinition = apps.get_model('calculators', 'CalculatorDefinition')
    slugs = [d["slug"] for d in get_calculator_definitions()]
    CalculatorDefinition.objects.filter(slug__in=slugs).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0003_populate_units'),
    ]

    operations = [
        migrations.RunPython(populate_calculator_definitions, reverse_calculator_definitions),
    ]
