# Generated by Django 6.0.1 on 2026-02-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0004_populate_calculator_definitions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatordefinition',
            name='definition',
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('length', 'Długość'), ('mass', 'Masa'), ('time', 'Czas'), ('area', 'Powierzchnia'), ('volume', 'Objętość'), ('force', 'Siła'), ('pressure', 'Ciśnienie'), ('energy', 'Energia'), ('power', 'Moc'), ('temperature', 'Temperatura'), ('currency', 'Waluta'), ('velocity', 'Prędkość'), ('dimensionless', 'Bezjednostkowe')], max_length=50, verbose_name='Typ jednostki'),
        ),
    ]
