# Generated by Django 5.2.10 on 2026-02-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0005_remove_calculatordefinition_definition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatorresult',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Wyniki zablokowane'),
        ),
    ]
