# Generated by Django 6.0.3 on 2026-03-25 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0006_calculatorresult_is_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCalculatorPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_new', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena (nowy resurs)')),
                ('price_recurring', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena (ponowny resurs)')),
                ('calculator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculators.calculatordefinition', verbose_name='Kalkulator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_prices', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Indywidualna cena kalkulatora',
                'verbose_name_plural': 'Indywidualne ceny kalkulatorów',
                'unique_together': {('user', 'calculator')},
            },
        ),
    ]
