# Generated by Django 6.0.3 on 2026-03-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0007_usercalculatorprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatordefinition',
            name='premium_cost_recurring',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=10, verbose_name='Koszt premium (ponowny resurs)'),
        ),
        migrations.AlterField(
            model_name='calculatordefinition',
            name='premium_cost',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Koszt premium (nowy resurs)'),
        ),
    ]
