# Generated by Django 6.0.3 on 2026-03-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0008_calculatordefinition_premium_cost_recurring_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCalculatorPrice',
        ),
    ]
