# Generated by Django 6.0.1 on 2026-02-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Imię i nazwisko')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa firmy')),
                ('scope_of_activities', models.TextField(blank=True, verbose_name='Zakres czynności')),
                ('contact_details', models.TextField(blank=True, verbose_name='Dane kontaktowe')),
                ('voivodeship', models.CharField(blank=True, choices=[('dolnośląskie', 'dolnośląskie'), ('kujawsko-pomorskie', 'kujawsko-pomorskie'), ('lubelskie', 'lubelskie'), ('lubuskie', 'lubuskie'), ('łódzkie', 'łódzkie'), ('małopolskie', 'małopolskie'), ('mazowieckie', 'mazowieckie'), ('opolskie', 'opolskie'), ('podkarpackie', 'podkarpackie'), ('podlaskie', 'podlaskie'), ('pomorskie', 'pomorskie'), ('śląskie', 'śląskie'), ('świętokrzyskie', 'świętokrzyskie'), ('warmińsko-mazurskie', 'warmińsko-mazurskie'), ('wielkopolskie', 'wielkopolskie'), ('zachodniopomorskie', 'zachodniopomorskie')], max_length=100, verbose_name='Województwo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Specjalista',
                'verbose_name_plural': 'Specjaliści',
                'ordering': ['full_name', 'company_name'],
            },
        ),
    ]
